services:
  flask:
    image: public.ecr.aws/f7y3w4q3/unianalytics-docker:latest
    ports:
      - "80:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_MESSAGE_QUEUE_URL=${REDIS_MESSAGE_QUEUE_URL}
